clientId: here-goes-your-client-id
clientSecret: here-goes-your-client-secret
tokenUrl: https://example.com/oauth2/token
usePolicyFile: true
usePolicyService: false
policyUpdateInterval: 600
policyHost: policy.example.com
policyProjectId: some-project-id
policyId: some-policy-id
