// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHeadV2ListsProjectIDPolicyIDParams creates a new HeadV2ListsProjectIDPolicyIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHeadV2ListsProjectIDPolicyIDParams() *HeadV2ListsProjectIDPolicyIDParams {
	return &HeadV2ListsProjectIDPolicyIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHeadV2ListsProjectIDPolicyIDParamsWithTimeout creates a new HeadV2ListsProjectIDPolicyIDParams object
// with the ability to set a timeout on a request.
func NewHeadV2ListsProjectIDPolicyIDParamsWithTimeout(timeout time.Duration) *HeadV2ListsProjectIDPolicyIDParams {
	return &HeadV2ListsProjectIDPolicyIDParams{
		timeout: timeout,
	}
}

// NewHeadV2ListsProjectIDPolicyIDParamsWithContext creates a new HeadV2ListsProjectIDPolicyIDParams object
// with the ability to set a context for a request.
func NewHeadV2ListsProjectIDPolicyIDParamsWithContext(ctx context.Context) *HeadV2ListsProjectIDPolicyIDParams {
	return &HeadV2ListsProjectIDPolicyIDParams{
		Context: ctx,
	}
}

// NewHeadV2ListsProjectIDPolicyIDParamsWithHTTPClient creates a new HeadV2ListsProjectIDPolicyIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewHeadV2ListsProjectIDPolicyIDParamsWithHTTPClient(client *http.Client) *HeadV2ListsProjectIDPolicyIDParams {
	return &HeadV2ListsProjectIDPolicyIDParams{
		HTTPClient: client,
	}
}

/*
HeadV2ListsProjectIDPolicyIDParams contains all the parameters to send to the API endpoint

	for the head v2 lists project ID policy ID operation.

	Typically these are written to a http.Request.
*/
type HeadV2ListsProjectIDPolicyIDParams struct {

	/* IfModifiedSince.

	   Conditional header for active Policy last modified date in [HTTP-date format](https://www.rfc-editor.org/rfc/rfc9110.html#name-if-modified-since)
	*/
	IfModifiedSince *string

	/* IfNoneMatch.

	   Conditional header for active Policy ETag.
	*/
	IfNoneMatch *string

	/* PolicyID.

	   Policy ID
	*/
	PolicyID string

	/* ProjectID.

	   Project ID
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the head v2 lists project ID policy ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadV2ListsProjectIDPolicyIDParams) WithDefaults() *HeadV2ListsProjectIDPolicyIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the head v2 lists project ID policy ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadV2ListsProjectIDPolicyIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithTimeout(timeout time.Duration) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithContext(ctx context.Context) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithHTTPClient(client *http.Client) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfModifiedSince adds the ifModifiedSince to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithIfModifiedSince(ifModifiedSince *string) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetIfModifiedSince(ifModifiedSince)
	return o
}

// SetIfModifiedSince adds the ifModifiedSince to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetIfModifiedSince(ifModifiedSince *string) {
	o.IfModifiedSince = ifModifiedSince
}

// WithIfNoneMatch adds the ifNoneMatch to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithIfNoneMatch(ifNoneMatch *string) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetIfNoneMatch(ifNoneMatch)
	return o
}

// SetIfNoneMatch adds the ifNoneMatch to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetIfNoneMatch(ifNoneMatch *string) {
	o.IfNoneMatch = ifNoneMatch
}

// WithPolicyID adds the policyID to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithPolicyID(policyID string) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetPolicyID(policyID string) {
	o.PolicyID = policyID
}

// WithProjectID adds the projectID to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) WithProjectID(projectID string) *HeadV2ListsProjectIDPolicyIDParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the head v2 lists project ID policy ID params
func (o *HeadV2ListsProjectIDPolicyIDParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *HeadV2ListsProjectIDPolicyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfModifiedSince != nil {

		// header param If-Modified-Since
		if err := r.SetHeaderParam("If-Modified-Since", *o.IfModifiedSince); err != nil {
			return err
		}
	}

	if o.IfNoneMatch != nil {

		// header param If-None-Match
		if err := r.SetHeaderParam("If-None-Match", *o.IfNoneMatch); err != nil {
			return err
		}
	}

	// path param policyID
	if err := r.SetPathParam("policyID", o.PolicyID); err != nil {
		return err
	}

	// path param projectID
	if err := r.SetPathParam("projectID", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
