// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new policy API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new policy API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new policy API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for policy API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetV2Lists(params *GetV2ListsParams, opts ...ClientOption) (*GetV2ListsOK, error)

	GetV2ListsProjectIDPolicyID(params *GetV2ListsProjectIDPolicyIDParams, opts ...ClientOption) (*GetV2ListsProjectIDPolicyIDOK, *GetV2ListsProjectIDPolicyIDPartialContent, error)

	HeadV2ListsProjectIDPolicyID(params *HeadV2ListsProjectIDPolicyIDParams, opts ...ClientOption) (*HeadV2ListsProjectIDPolicyIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetV2Lists retrieves multiple active policy lists
*/
func (a *Client) GetV2Lists(params *GetV2ListsParams, opts ...ClientOption) (*GetV2ListsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV2ListsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV2Lists",
		Method:             "GET",
		PathPattern:        "/v2/lists",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetV2ListsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV2ListsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetV2Lists: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetV2ListsProjectIDPolicyID retrieves a current active policy list
*/
func (a *Client) GetV2ListsProjectIDPolicyID(params *GetV2ListsProjectIDPolicyIDParams, opts ...ClientOption) (*GetV2ListsProjectIDPolicyIDOK, *GetV2ListsProjectIDPolicyIDPartialContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV2ListsProjectIDPolicyIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV2ListsProjectIDPolicyID",
		Method:             "GET",
		PathPattern:        "/v2/lists/{projectID}/{policyID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetV2ListsProjectIDPolicyIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *GetV2ListsProjectIDPolicyIDOK:
		return value, nil, nil
	case *GetV2ListsProjectIDPolicyIDPartialContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for policy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
HeadV2ListsProjectIDPolicyID retrieves current active policy header information
*/
func (a *Client) HeadV2ListsProjectIDPolicyID(params *HeadV2ListsProjectIDPolicyIDParams, opts ...ClientOption) (*HeadV2ListsProjectIDPolicyIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHeadV2ListsProjectIDPolicyIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HeadV2ListsProjectIDPolicyID",
		Method:             "HEAD",
		PathPattern:        "/v2/lists/{projectID}/{policyID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &HeadV2ListsProjectIDPolicyIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HeadV2ListsProjectIDPolicyIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HeadV2ListsProjectIDPolicyID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
