// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolicyTag policy tag
//
// swagger:model policy.Tag
type PolicyTag struct {

	// name
	// Example: Country
	Name string `json:"name,omitempty"`

	// values
	// Example: ["Australia"]
	Values []string `json:"values"`
}

// Validate validates this policy tag
func (m *PolicyTag) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policy tag based on context it is used
func (m *PolicyTag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyTag) UnmarshalBinary(b []byte) error {
	var res PolicyTag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
